<a href="https://colab.research.google.com/github/hoangminhanh/twsm-homework/blob/main/HW4_NewsGroup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import pickle
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import Binarizer
import pandas as pd

# Import the dataset

In [ ]:
# Import dataset
df = pd.read_json('https://raw.githubusercontent.com/selva86/datasets/master/newsgroups.json')
df.head()

,content,target,target_names
0,From: lerxst@wam.umd.edu (where's my thing)\nS...,7,rec.autos
1,From: guykuo@carson.u.washington.edu (Guy Kuo)...,4,comp.sys.mac.hardware
2,From: twillis@ec.ecn.purdue.edu (Thomas E Will...,4,comp.sys.mac.hardware
3,From: jgreen@amber (Joe Green)\nSubject: Re: W...,1,comp.graphics
4,From: jcm@head-cfa.harvard.edu (Jonathan McDow...,14,sci.space

In [ ]:
import pickle
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import Binarizer
import numpy as np

In [ ]:
# Importing the stemmed News Group data

from google.colab import drive 
drive.mount("/content/drive")

data_path = "/content/drive/MyDrive/TWSM"
infile = open(data_path+'/Stemmed.pkl','rb')
data = pickle.load(infile)

stem = pd.DataFrame(data, columns=["stemmed_text"])
stem.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

                                        stemmed_text
0  wonder enlighten car saw dai door sport car lo...
1  nntp post host carson washington edu fair numb...
2  folk mac plu final gave ghost weekend start li...
3  nntp post host amber ssd csd harri com robert ...
4  articl cowcb world std com tombak world std co...

In [ ]:
# Importing the lemmatized News Group data

infile = open(data_path+'/Lemma.pkl','rb')
data = pickle.load(infile)

lemma = pd.DataFrame(data, columns=["lemmatized_text"])
lemma.head()

                                     lemmatized_text
0  wonder enlighten car see day door sport car lo...
1  nntp post host carson washington edu fair numb...
2  folks mac plus finally give ghost weekend star...
3  nntp post host amber ssd csd harris com robert...
4  article cowcb world std com tombaker world std...

In [ ]:
# Importing the dataset to get the targets

df = pd.read_json('https://raw.githubusercontent.com/selva86/datasets/master/newsgroups.json')
df.head()

,content,target,target_names
0,From: lerxst@wam.umd.edu (where's my thing)\nS...,7,rec.autos
1,From: guykuo@carson.u.washington.edu (Guy Kuo)...,4,comp.sys.mac.hardware
2,From: twillis@ec.ecn.purdue.edu (Thomas E Will...,4,comp.sys.mac.hardware
3,From: jgreen@amber (Joe Green)\nSubject: Re: W...,1,comp.graphics
4,From: jcm@head-cfa.harvard.edu (Jonathan McDow...,14,sci.space

In [ ]:
# Examine the dataset

print('Possible tagret values:')
print(df.target_names.unique())
print(' ')
print('Class distribution:')
print(df.target_names.value_counts())

Possible tagret values:
['rec.autos' 'comp.sys.mac.hardware' 'comp.graphics' 'sci.space'
 'talk.politics.guns' 'sci.med' 'comp.sys.ibm.pc.hardware'
 'comp.os.ms-windows.misc' 'rec.motorcycles' 'talk.religion.misc'
 'misc.forsale' 'alt.atheism' 'sci.electronics' 'comp.windows.x'
 'rec.sport.hockey' 'rec.sport.baseball' 'soc.religion.christian'
 'talk.politics.mideast' 'talk.politics.misc' 'sci.crypt']

Class distribution:
rec.sport.hockey            600
soc.religion.christian      599
rec.motorcycles             598
rec.sport.baseball          597
sci.crypt                   595
rec.autos                   594
sci.med                     594
comp.windows.x              593
sci.space                   593
comp.os.ms-windows.misc     591
sci.electronics             591
comp.sys.ibm.pc.hardware    590
misc.forsale                585
comp.graphics               584
comp.sys.mac.hardware       578
talk.politics.mideast       564
talk.politics.guns          546
alt.atheism                 480
talk.politics.misc          465
talk.religion.misc          377
Name: target_names, dtype: int64

In [ ]:
# Combining the stemmed and lemmatized text with their targets 

stem_df = pd.concat([stem, df], axis=1).drop(["content"], axis=1)

lemma_df = pd.concat([lemma, df], axis=1).drop(["content"], axis=1)

In [ ]:
stem_df.head()

,stemmed_text,target,target_names
0,wonder enlighten car saw dai door sport car lo...,7,rec.autos
1,nntp post host carson washington edu fair numb...,4,comp.sys.mac.hardware
2,folk mac plu final gave ghost weekend start li...,4,comp.sys.mac.hardware
3,nntp post host amber ssd csd harri com robert ...,1,comp.graphics
4,articl cowcb world std com tombak world std co...,14,sci.space

In [ ]:
lemma_df.head()

,lemmatized_text,target,target_names
0,wonder enlighten car see day door sport car lo...,7,rec.autos
1,nntp post host carson washington edu fair numb...,4,comp.sys.mac.hardware
2,folks mac plus finally give ghost weekend star...,4,comp.sys.mac.hardware
3,nntp post host amber ssd csd harris com robert...,1,comp.graphics
4,article cowcb world std com tombaker world std...,14,sci.space

In [ ]:
# Train test split 

from sklearn.model_selection import train_test_split

X_stem = stem_df.stemmed_text
y_stem = stem_df.target

X_train_stem, X_test_stem, y_train_stem, y_test_stem = train_test_split(X_stem, y_stem, test_size=0.1)

X_lemma = lemma_df.lemmatized_text
y_lemma = lemma_df.target

X_train_lemma, X_test_lemma, y_train_lemma, y_test_lemma = train_test_split(X_lemma, y_lemma, test_size=0.1)

# Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB

# Stemmed
abs_s = CountVectorizer(max_df=0.95, min_df=0.05)
rel_s = TfidfVectorizer(max_df=0.95, min_df=0.05,use_idf=False, norm='l1')
tfidf_s = TfidfVectorizer(max_df=0.95, min_df=0.05, smooth_idf=False)
bayes_s = MultinomialNB()

#Lemmatized

abs_l = CountVectorizer(max_df=0.95, min_df=0.05)
rel_l = TfidfVectorizer(max_df=0.95, min_df=0.05,use_idf=False, norm='l1')
tfidf_l = TfidfVectorizer(max_df=0.95, min_df=0.05, smooth_idf=False)
bayes_l = MultinomialNB()

## Absolute Frequency

In [ ]:
# Stemmed 

X_train_stem_abs = abs_s.fit_transform(X_train_stem).toarray()
X_test_stem_abs = abs_s.transform(X_test_stem).toarray()

bayes_s.fit(X_train_stem_abs, y_train_stem)

y_pred_stem_abs = bayes_s.predict(X_test_stem_abs)

from sklearn.metrics import accuracy_score, classification_report
print('Train accuracy: ', bayes_s.score(X_train_stem_abs, y_train_stem))
print('Test accuracy: ', accuracy_score(y_pred_stem_abs, y_test_stem))

Train accuracy:  0.5173836181496759
Test accuracy:  0.45141342756183744

In [ ]:
# Lemmatized 

X_train_lemma_abs = abs_l.fit_transform(X_train_lemma).toarray()
X_test_lemma_abs = abs_l.transform(X_test_lemma).toarray()

bayes_l.fit(X_train_lemma_abs, y_train_lemma)

y_pred_lemma_abs = bayes_l.predict(X_test_lemma_abs)

print('Train accuracy: ', bayes_l.score(X_train_lemma_abs, y_train_lemma))
print('Test accuracy: ', accuracy_score(y_pred_lemma_abs, y_test_lemma))

Train accuracy:  0.4866430956590061
Test accuracy:  0.43551236749116606

## TF-IDF

In [ ]:
# Stemmed

X_train_stem_tfidf = tfidf_s.fit_transform(X_train_stem).toarray()
X_test_stem_tfidf = tfidf_s.transform(X_test_stem).toarray()

bayes_s.fit(X_train_stem_tfidf, y_train_stem)

y_pred_stem_tfidf = bayes_s.predict(X_test_stem_tfidf)

print('Train accuracy: ', bayes_s.score(X_train_stem_tfidf, y_train_stem))
print('Test accuracy: ', accuracy_score(y_pred_stem_tfidf, y_test_stem))

Train accuracy:  0.5523472795128659
Test accuracy:  0.48586572438162545

In [ ]:
# Lemmatized 

X_train_lemma_tfidf = tfidf_l.fit_transform(X_train_lemma).toarray()
X_test_lemma_tfidf = tfidf_l.transform(X_test_lemma).toarray()

bayes_l.fit(X_train_lemma_tfidf, y_train_lemma)

y_pred_lemma_tfidf = bayes_l.predict(X_test_lemma_tfidf)

print('Train accuracy: ', bayes_l.score(X_train_lemma_tfidf, y_train_lemma))
print('Test accuracy: ', accuracy_score(y_pred_lemma_tfidf, y_test_lemma))

Train accuracy:  0.5292673345118837
Test accuracy:  0.4558303886925795

# Neural Networks